api_push_register:
    path:           /api/v1.0/push/register
    defaults:       { _controller: AuthBucketPushBundle:Push:register }
    methods:        [ POST ]

api_push_unregister:
    path:           /api/v1.0/push/unregister
    defaults:       { _controller: AuthBucketPushBundle:Push:unregister }
    methods:        [ POST ]

api_push_send:
    path:           /api/v1.0/push/send
    defaults:       { _controller: AuthBucketPushBundle:Push:send }
    methods:        [ POST ]

api_service_create:
    path:           /api/v1.0/service.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Service:create }
    methods:        [ POST ]
    requirements:
        _format:    json|xml

api_service_read:
    path:           /api/v1.0/service/{id}.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Service:read }
    methods:        [ GET ]
    requirements:
        _format:    json|xml

api_service_update:
    path:           /api/v1.0/service/{id}.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Service:update }
    methods:        [ PUT ]
    requirements:
        _format:    json|xml

api_service_delete:
    path:           /api/v1.0/service/{id}.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Service:delete }
    methods:        [ DELETE ]
    requirements:
        _format:    json|xml

api_service_list:
    path:           /api/v1.0/service.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Service:list }
    methods:        [ GET ]
    requirements:
        _format:    json|xml

api_device_create:
    path:           /api/v1.0/device.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Device:create }
    methods:        [ POST ]
    requirements:
        _format:    json|xml

api_device_read:
    path:           /api/v1.0/device/{id}.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Device:read }
    methods:        [ GET ]
    requirements:
        _format:    json|xml

api_device_update:
    path:           /api/v1.0/device/{id}.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Device:update }
    methods:        [ PUT ]
    requirements:
        _format:    json|xml

api_device_delete:
    path:           /api/v1.0/device/{id}.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Device:delete }
    methods:        [ DELETE ]
    requirements:
        _format:    json|xml

api_device_list:
    path:           /api/v1.0/device.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Device:list }
    methods:        [ GET ]
    requirements:
        _format:    json|xml

api_message_create:
    path:           /api/v1.0/message.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Message:create }
    methods:        [ POST ]
    requirements:
        _format:    json|xml

api_message_read:
    path:           /api/v1.0/message/{id}.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Message:read }
    methods:        [ GET ]
    requirements:
        _format:    json|xml

api_message_update:
    path:           /api/v1.0/message/{id}.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Message:update }
    methods:        [ PUT ]
    requirements:
        _format:    json|xml

api_message_delete:
    path:           /api/v1.0/message/{id}.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Message:delete }
    methods:        [ DELETE ]
    requirements:
        _format:    json|xml

api_message_list:
    path:           /api/v1.0/message.{_format}
    defaults:       { _controller: AuthBucketPushBundle:Message:list }
    methods:        [ GET ]
    requirements:
        _format:    json|xml
