parameters:
    authbucket_push.service_handler:
        apns:   AuthBucket\Push\ServiceType\ApnsServiceTypeHandler
        gcm:    AuthBucket\Push\ServiceType\GcmServiceTypeHandler

services:
    authbucket_push.exception_listener:
        class: AuthBucket\Push\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -8 }

    authbucket_push.service_handler.factory:
        class: AuthBucket\Push\ServiceType\ServiceTypeHandlerFactory
        arguments:
            - "@security.context"
            - "@validator"
            - "@authbucket_push.model_manager.factory"
            - "%authbucket_push.service_handler%"

    authbucket_push.push_controller:
        class: AuthBucket\Push\Controller\PushController
        arguments:
            - "@security.context"
            - "@validator"
            - "@authbucket_push.model_manager.factory"
            - "@authbucket_push.service_handler.factory"

    authbucket_push.service_controller:
        class: AuthBucket\Push\Controller\ServiceController
        arguments:
            - "@validator"
            - "@serializer"
            - "@authbucket_push.model_manager.factory"

    authbucket_push.device_controller:
        class: AuthBucket\Push\Controller\DeviceController
        arguments:
            - "@validator"
            - "@serializer"
            - "@authbucket_push.model_manager.factory"

    authbucket_push.message_controller:
        class: AuthBucket\Push\Controller\MessageController
        arguments:
            - "@validator"
            - "@serializer"
            - "@authbucket_push.model_manager.factory"
