authbucketpushbundle:
    prefix:     /api/push
    resource:   "@AuthBucketPushBundle/Resources/config/routing.yml"

testbundle:
    prefix:     /
    resource:   "@TestBundle/Resources/config/routing.yml"
