security:
    encoders:
        Symfony\Component\Security\Core\User\User:  plaintext

    providers:
        admin:
            memory:
                users:
                    admin:          { roles: 'ROLE_ADMIN', password: secrete }

    firewalls:
        admin:
            pattern:                ^/admin
            http_basic:             ~
            provider:               admin

        api:
            pattern:                ^/api
            oauth2_resource:
                resource_type:      debug_endpoint
                scope:              ~
                options:
                    debug_endpoint: 'http://oauth2-symfony-bundle.authbucket.com/api/oauth2/debug'
                    cache:          false
