parameters:
    authbucket_push.service_handler:
        apns:   AuthBucket\Push\ServiceType\ApnsServiceTypeHandler
        gcm:    AuthBucket\Push\ServiceType\GcmServiceTypeHandler

services:
    authbucket_push.exception_listener:
        class: AuthBucket\Push\EventListener\ExceptionListener
        arguments:
            - "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: -2 }

    authbucket_push.service_handler.factory:
        class: AuthBucket\Push\ServiceType\ServiceTypeHandlerFactory
        arguments:
            - "@security.token_storage"
            - "@validator"
            - "@authbucket_push.model_manager.factory"
            - "%authbucket_push.service_handler%"

    authbucket_push.push_controller:
        class: AuthBucket\Push\Controller\PushController
        arguments:
            - "@security.token_storage"
            - "@validator"
            - "@authbucket_push.model_manager.factory"
            - "@authbucket_push.service_handler.factory"
